<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-KB6UDKRL" failures="1" tests="2" name="Test" time="37.729" errors="0" timestamp="2021-10-21T15:15:16 IST">
  <testcase classname="scriptsContacts.TC_12_createcontact_assignedTo_Teamselling_Group" name="createcontact_assignedTo_Teamselling_Group" time="6.317"/>
  <testcase classname="scriptsContacts.TC_11_createcontact_assignedTo_Support_Group" name="createcontact_assignedTo_Support_Group" time="6.159">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at scriptsContacts.TC_11_createcontact_assignedTo_Support_Group.createcontact_assignedTo_Support_Group(TC_11_createcontact_assignedTo_Support_Group.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createcontact_assignedTo_Support_Group -->
</testsuite> <!-- Test -->
